# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 150
  # Number of characters for headings
  heading_line_length: 100
  code_blocks: false

# MD033/html - Inline HTML
MD033:
  allowed_elements: ["details", "summary", "br", "small"]
