---
name: Lint Code Base

on:
  
  push:
    branches: [main]
  
  pull_request:

jobs:
  call-super-linter:

    name: Call Super-Linter

    # use Reusable Workflows to call my linter config remotely
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    
    permissions:
      contents: read # clone the repo to lint
      statuses: write #read/write to repo custom statuses

    uses: bretfisher/super-linter-workflow/.github/workflows/super-linter.yaml@main
    
    with:
      devops-only: true
      filter-regex-exclude: .*compose-sample-3/html/.*
